### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_api#4]

**Comment by Lauraillouz** [comment]
https://github.com/goldbergyoni/nodebestpractices

@mridha-emran Check that out, it's very interesting, and useful to know how to refactor the backend

**Comment by Lauraillouz** [comment]
https://github.com/goldbergyoni/nodebestpractices

**Comment by gaeVG** [comment]
@mridha-emran, have you been able to advance about refactoring. Otherwise as said I can start the structure if you prefer 🤗

**Comment by Lauraillouz** [comment]
To be merged

**Comment by gaeVG** [comment]
I tried to clean and structure as much as possible, @Lauraillouz , @mridha-emran, tell me what you think
